######################################################################
# Automatically generated by qmake (1.07a) Sun May 10 22:08:06 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .
LIBS += -lsctp

# Input
HEADERS += SCTPServerSocket.h
SOURCES += main.cpp SCTPServerSocket.cpp
