######################################################################
# Automatically generated by qmake (1.07a) Tue Sep 2 21:43:38 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += canvas.h
SOURCES += canvas.cpp main.cpp
