######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 19 17:09:10 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += lineedits.h
SOURCES += lineedits.cpp main.cpp
