######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 08:51:44 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
