######################################################################
# Automatically generated by qmake (1.07a) Sun Mar 1 17:04:20 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += imagedata.h MyCameraWindow.h imagedata.h ClientSocket.h ServerSocket.h Socket.h transmit.h
SOURCES += main.cpp MyCameraWindow.cpp ClientSocket.cpp ServerSocket.cpp Socket.cpp transmit.cpp
