######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 8 00:00:05 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += caterpillar.h mydebug.h myview.h
SOURCES += caterpillar.cpp main.cpp myview.cpp
