######################################################################
# Automatically generated by qmake (1.07a) Thu Oct 16 23:15:40 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += caterpillar.h mydebug.h myqcanvas.h myview.h
SOURCES += caterpillar.cpp main.cpp myqcanvas.cpp myview.cpp
