######################################################################
# Automatically generated by qmake (1.07a) Fri Oct 17 10:29:21 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += caterpillar.h mydebug.h myqcanvas.h myview.h
SOURCES += caterpillar.cpp main.cpp myqcanvas.cpp myview.cpp
