######################################################################
# Automatically generated by qmake (1.07a) Wed May 20 11:04:17 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += ..

LIBS += -lsctp

# Input
HEADERS += MyCameraWindow.h
SOURCES += main.cpp MyCameraWindow.cpp
