######################################################################
# Automatically generated by qmake (1.07a) Mon Aug 25 12:04:34 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h gamebrd.h lcdrange.h
SOURCES += cannon.cpp gamebrd.cpp lcdrange.cpp main.cpp
