######################################################################
# Automatically generated by qmake (1.07a) Wed May 20 11:04:17 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += ..

# 設定要檢示錯誤訊息
# DEFINES += REN_DEBUG

LIBS += -lsctp

# Input
HEADERS += MyCameraWindow.h
SOURCES += main.cpp MyCameraWindow.cpp
