######################################################################
# Automatically generated by qmake (1.07a) Thu Oct 23 10:51:25 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += ddlabel.h
SOURCES += ddlabel.cpp main.cpp
