######################################################################
# Automatically generated by qmake (1.07a) Wed May 6 16:43:45 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

LIBS += -lsctp

# Input
SOURCES += main.cpp
