######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 19 23:21:35 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += checklists.h
SOURCES += checklists.cpp main.cpp
