######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 19 12:08:00 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
