######################################################################
# Automatically generated by qmake (1.07a) Sat Aug 23 17:03:49 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h lcdrange.h
SOURCES += cannon.cpp lcdrange.cpp main.cpp
