######################################################################
# Automatically generated by qmake (1.07a) Sat Dec 20 16:04:30 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
