######################################################################
# Automatically generated by qmake (1.07a) Mon Dec 22 15:14:47 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += myevent.h mywidget.h
SOURCES += main.cpp myevent.cpp mywidget.cpp
