######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 16 22:57:38 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
