######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 19 10:57:41 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += dclock.h
SOURCES += dclock.cpp main.cpp
