######################################################################
# Automatically generated by qmake (1.07a) Thu Feb 19 13:52:40 2009
######################################################################

TEMPLATE = app
TARGET = Dr.ta
DEPENDPATH += .
CONFIG -= moc
LIBS += -lcv -lhighgui
INCLUDEPATH += .

# Input
SOURCES += main.cpp MyCameraWindow.cpp QOpenCVWidget.cpp MyCanvas.cpp
HEADERS += MyCameraWindow.h QOpenCVWidget.h MyCanvas.h
