######################################################################
# Automatically generated by qmake (1.07a) Thu Aug 21 11:13:23 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
