######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 20 23:33:49 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += dropsite.h secret.h
SOURCES += dropsite.cpp main.cpp secret.cpp
