######################################################################
# Automatically generated by qmake (1.07a) Fri May 1 20:26:57 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# DEFINES = D_MYDEFINE

# Input
SOURCES += main.cpp
