######################################################################
# Automatically generated by qmake (1.07a) Wed May 20 11:04:17 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += ..

# 加入可以檢視傳送接收訊息的註解
# DEFINES += REN_DEBUG

LIBS += -lsctp

# Input
HEADERS += MyCameraWindow.h
SOURCES += main.cpp MyCameraWindow.cpp
