######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 10:20:12 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
