######################################################################
# Automatically generated by qmake (1.07a) Wed May 6 17:37:45 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .
LIBS += -lsctp

# Input
HEADERS += message.h
SOURCES += main.cpp message.cpp
