######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 19 21:04:36 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
