######################################################################
# Automatically generated by qmake (1.07a) Fri Oct 24 12:03:50 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mybutton.h mydebug.h myqcanvas.h mysource.h view.h
SOURCES += main.cpp mybutton.cpp myqcanvas.cpp mysource.cpp view.cpp
