######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 23 15:05:30 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
