######################################################################
# Automatically generated by qmake (1.07a) Thu Oct 23 23:23:45 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mydebug.h myqcanvas.h mysource.h view.h
SOURCES += main.cpp myqcanvas.cpp mysource.cpp view.cpp
