######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 12:03:59 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
