FOLDER	= lib client/version01 server/01_iterative_server

.PHONY: everything all clean distclean

everything:
	cd lib;$(MAKE) $@
	cd client/version01;$(MAKE) $@
	cd server/01_iterative_server;$(MAKE) $@
all:
	cd lib;$(MAKE) $@
	cd client/version01;$(MAKE) $@
	cd server/01_iterative_server;$(MAKE) $@

clean:
	cd lib;$(MAKE) $@
	cd client/version01;$(MAKE) $@
	cd server/01_iterative_server;$(MAKE) $@

distclean:
	cd lib;$(MAKE) $@
	cd client/version01;$(MAKE) $@
	cd server/01_iterative_server;$(MAKE) $@
