######################################################################
# Automatically generated by qmake (1.07a) Sat Dec 20 17:32:35 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
