######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 21:13:58 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
