######################################################################
# Automatically generated by qmake (1.07a) Sun Aug 24 23:02:24 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h gamebrd.h lcdrange.h
SOURCES += cannon.cpp gamebrd.cpp lcdrange.cpp main.cpp
