######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 15:00:08 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
