######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 23:08:29 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h lcdrange.h
SOURCES += cannon.cpp lcdrange.cpp main.cpp
