######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 16 22:29:38 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += showpush.h
SOURCES += main.cpp showpush.cpp
