######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 17:36:13 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
SOURCES += main.cpp mywidget.cpp
