######################################################################
# Automatically generated by qmake (1.07a) Wed Sep 3 16:59:18 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
