######################################################################
# Automatically generated by qmake (1.07a) Mon Mar 2 10:53:39 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += client.cpp
