
CC	= gcc

LIBS	= -lsctp

OBJ	= sctpclient01.o

TARGET	= sctpclient01

.PHONY: everything all clean distclean

everything: $(TARGET)

all: distclean everything

clean:
	rm -fv $(OBJ)

distclean: clean
	rm -fv $(TARGET)

$(OBJ): sctpclient01.c
	$(CC) -c $< -o $@

$(TARGET):$(OBJ)
	$(CC) $(LIBS) $< -o $@
