######################################################################
# Automatically generated by qmake (1.07a) Fri May 1 14:12:53 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += client.cpp
