######################################################################
# Automatically generated by qmake (1.07a) Tue Sep 2 14:53:51 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
