######################################################################
# Automatically generated by qmake (1.07a) Sun Aug 24 20:52:22 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h lcdrange.h
SOURCES += cannon.cpp lcdrange.cpp main.cpp
