######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 19 22:50:52 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
