######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 19 18:46:07 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
