######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 16 23:25:00 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
