######################################################################
# Automatically generated by qmake (1.07a) Wed Sep 3 10:29:06 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += myqcanvas.h view.h
SOURCES += main.cpp myqcanvas.cpp view.cpp
