######################################################################
# Automatically generated by qmake (1.07a) Wed Jun 17 14:16:37 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += . ..

LIBS += -lsctp -lcv -lhighgui

# 設定是否檢視訊息
# DEFINES += REN_DEBUG

# Input
HEADERS += SctpSocketServer.h ../common.h
SOURCES += main.cpp SctpSocketServer.cpp
