######################################################################
# Automatically generated by qmake (1.07a) Wed Jun 17 14:16:37 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += . ..

LIBS += -lsctp -lcv -lhighgui

# Input
HEADERS += SctpSocketServer.h ../common.h
SOURCES += main.cpp SctpSocketServer.cpp
