######################################################################
# Automatically generated by qmake (1.07a) Fri Oct 20 16:05:40 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += dlgcarsetting.ui.h initial_set.ui.h settimeratio.ui.h initial_set_dsrc.ui.h 
INTERFACES += dlgcarsetting.ui initial_set.ui settimeratio.ui initial_set_dsrc.ui.h
