######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 19 16:03:06 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += listboxcombo.h
SOURCES += listboxcombo.cpp main.cpp
