######################################################################
# Automatically generated by qmake (1.07a) Sun May 10 22:43:33 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .
LIBS += -lsctp

# Input
HEADERS += SCTPClientSocket.h
SOURCES += main.cpp SCTPClientSocket.cpp
