######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 19 21:41:29 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += simreader.h
SOURCES += main.cpp simreader.cpp
