######################################################################
# Automatically generated by qmake (1.07a) Thu Feb 19 18:50:37 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
