######################################################################
# Automatically generated by qmake (1.07a) Fri May 8 23:40:11 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += classA.h classB.h
SOURCES += classA.cpp classB.cpp main.cpp
