######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 22 23:33:12 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
