######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 14:53:36 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
