######################################################################
# Automatically generated by qmake (1.07a) Fri Feb 20 13:38:04 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += MyWidget.h
SOURCES += main.cpp MyWidget.cpp
