######################################################################
# Automatically generated by qmake (1.07a) Sun Dec 21 18:43:58 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
