######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 11:41:16 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += warnqvbox.h
SOURCES += main.cpp warnqvbox.cpp
