######################################################################
# Automatically generated by qmake (1.07a) Fri Aug 22 22:25:16 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += lcdrange.h
SOURCES += lcdrange.cpp main.cpp
